# Generated by Django 3.2.7 on 2021-09-11 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('town_or_city', models.CharField(blank=True, max_length=40)),
                ('about_me', models.TextField(blank=True, default='N/A', max_length=999)),
                ('occupation', models.CharField(max_length=100)),
                ('education_1', models.CharField(blank=True, default='N/A', max_length=100)),
                ('education_2', models.CharField(blank=True, default='N/A', max_length=100)),
                ('education_3', models.CharField(blank=True, default='N/A', max_length=100)),
                ('social_link_1', models.TextField(blank=True, default='N/A', max_length=999)),
                ('social_link_2', models.TextField(blank=True, default='N/A', max_length=999)),
                ('social_link_3', models.TextField(blank=True, default='N/A', max_length=999)),
                ('social_link_4', models.TextField(blank=True, default='N/A', max_length=999)),
                ('job_1', models.CharField(blank=True, default='N/A', max_length=100)),
                ('company_1', models.CharField(blank=True, default='N/A', max_length=100)),
                ('time_at_employer_1', models.CharField(blank=True, default='N/A', max_length=100)),
                ('job_2', models.CharField(blank=True, default='N/A', max_length=100)),
                ('company_2', models.CharField(blank=True, default='N/A', max_length=100)),
                ('time_at_employer_2', models.CharField(blank=True, default='N/A', max_length=100)),
                ('job_3', models.CharField(blank=True, default='N/A', max_length=100)),
                ('company_3', models.CharField(blank=True, default='N/A', max_length=100)),
                ('time_at_employer_3', models.CharField(blank=True, default='N/A', max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.TextField(blank=True, default='N/A', max_length=999)),
                ('strengths', models.CharField(blank=True, default='N/A', max_length=100)),
                ('weakness', models.CharField(blank=True, default='N/A', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
