# Generated by Django 3.2.7 on 2021-09-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210912_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_description',
            field=models.TextField(blank=True, default='N/A', max_length=999),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='social_link_1',
            field=models.TextField(blank=True, default='N/A', max_length=999),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='social_link_2',
            field=models.TextField(blank=True, default='N/A', max_length=999),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='social_link_3',
            field=models.TextField(blank=True, default='N/A', max_length=999),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='social_link_4',
            field=models.TextField(blank=True, default='N/A', max_length=999),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='social_type_1',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='social_type_2',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='social_type_3',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='social_type_4',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='town_or_city',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='video',
            field=models.TextField(blank=True, default='N/A', max_length=999),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, default='N/A', max_length=999),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_1',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_2',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_3',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education_1',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education_2',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education_3',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_1',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_2',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_3',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_link_1',
            field=models.TextField(blank=True, default='N/A', max_length=999),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_link_2',
            field=models.TextField(blank=True, default='N/A', max_length=999),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_link_3',
            field=models.TextField(blank=True, default='N/A', max_length=999),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_link_4',
            field=models.TextField(blank=True, default='N/A', max_length=999),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_type_1',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_type_2',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_type_3',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_type_4',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='strengths',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='time_at_employer_1',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='time_at_employer_2',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='time_at_employer_3',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='town_or_city',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='video',
            field=models.TextField(blank=True, default='N/A', max_length=999),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weakness',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
    ]
